const assetsFolder = "./AS_assets/";
const assetsSVGFolder = assetsFolder + "SVG/";
const classicExplosion = 'expl1.gif';
const strikeExplosion = 'expl_big.gif';
const mushroomExplosion = 'mushroom_1.gif';
const crashTimeout = 600;
const destroyedTargetStay = 20000;
const itemStay = 15000;
const fadeAnimTime = 8000;
//# sourceMappingURL=const.js.map